import { useState } from "react";
import TransactionGraph from "./TransactionGraph";
import "./index.css";

function App() {
  const [walletAddress, setWalletAddress] = useState("");
  const [isInvestigating, setIsInvestigating] = useState(false);
  const [showDashboard, setShowDashboard] = useState(false);
  const [error, setError] = useState("");
  const [progress, setProgress] = useState(0);

  const [investigationData, setInvestigationData] = useState(null);

  // =====================================================
  // BACKEND CONNECTION
  // =====================================================

  const investigateWallet = async () => {
    const response = await fetch("http://localhost:5000/investigate", {
      method: "POST",

      headers: {
        "Content-Type": "application/json",
      },

      body: JSON.stringify({
        wallet: walletAddress.trim(),
      }),
    });

    if (!response.ok) {
      throw new Error("Backend investigation failed.");
    }

    return await response.json();
  };


  // =====================================================
  // INVESTIGATION
  // =====================================================

  const handleInvestigation = async () => {
    setError("");

    if (!walletAddress.trim()) {
      setError("Please enter a wallet address.");
      return;
    }

    if (walletAddress.trim().length < 10) {
      setError("Invalid wallet address format.");
      return;
    }

    setIsInvestigating(true);
    setShowDashboard(false);
    setProgress(0);

    let currentProgress = 0;

    const progressInterval = setInterval(() => {
      currentProgress += 10;

      if (currentProgress >= 100) {
        currentProgress = 100;
        clearInterval(progressInterval);
      }

      setProgress(currentProgress);
    }, 180);

    try {
      // Send wallet address to backend
      const data = await investigateWallet();

      console.log("BACKEND RESPONSE:");
      console.log(data);

      setInvestigationData(data);

      setProgress(100);

      clearInterval(progressInterval);

      setTimeout(() => {
        setIsInvestigating(false);
        setShowDashboard(true);
      }, 400);

    } catch (err) {
      console.error(err);

      clearInterval(progressInterval);

      setIsInvestigating(false);
      setProgress(0);

      setError(
        "Could not connect to the investigation server. Make sure the backend is running."
      );
    }
  };


  // =====================================================
  // REPORT GENERATION
  // =====================================================

  const generateReport = () => {
    const data = investigationData;

    const report = `
========================================================
                 CHAKRAVYUH
          BLOCKCHAIN INVESTIGATION REPORT
========================================================

INVESTIGATION TARGET
${walletAddress}

--------------------------------------------------------
RISK ASSESSMENT
--------------------------------------------------------

Risk Level: ${data?.risk || "HIGH"}
Transactions: ${data?.transactions || 24}
Blockchain Hops: ${data?.blockchain_hops || 3}
Suspicious Points: ${data?.suspicious_points || 5}

--------------------------------------------------------
SUSPICIOUS ACTIVITY
--------------------------------------------------------

${
  data?.suspicious_activity
    ?.map(
      (item, index) =>
        `${index + 1}. ${item.title}
   ${item.description}
   Severity: ${item.severity}`
    )
    .join("\n\n") ||
  "No suspicious activity data available."
}

--------------------------------------------------------
VASP / EXCHANGE
--------------------------------------------------------

Name: ${data?.vasp?.name || "Unknown Exchange"}
Confidence: ${data?.vasp?.confidence || 78}%

--------------------------------------------------------
CONNECTED CASES
--------------------------------------------------------

${
  data?.connected_cases
    ?.map(
      (item) =>
        `Case #${item.id}
Description: ${item.description}
Match Type: ${item.type}`
    )
    .join("\n\n") ||
  "No connected cases available."
}

--------------------------------------------------------
REPORT STATUS
--------------------------------------------------------

Investigation completed successfully.

Generated by CHAKRAVYUH
Blockchain Investigation System

========================================================
`;

    const blob = new Blob([report], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.download = "CHAKRAVYUH_Investigation_Report.txt";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };


  // =====================================================
  // LOADING SCREEN
  // =====================================================

  if (isInvestigating) {
    return (
      <div className="loading-page">

        <div className="loading-container">

          <div className="loading-label">
            CHAKRAVYUH // DIGITAL FORENSICS
          </div>

          <h1>ANALYZING WALLET</h1>

          <div className="loading-wallet">
            {walletAddress}
          </div>

          <div className="progress-container">

            <div className="progress-bar">

              <div
                className="progress-fill"
                style={{
                  width: `${progress}%`,
                }}
              />

            </div>

            <div className="progress-number">
              {progress}%
            </div>

          </div>


          <div className="analysis-steps">

            <div className={`step ${progress >= 20 ? "active" : ""}`}>
              <span>01</span>
              Scanning transactions...
            </div>

            <div className={`step ${progress >= 40 ? "active" : ""}`}>
              <span>02</span>
              Tracing blockchain hops...
            </div>

            <div className={`step ${progress >= 60 ? "active" : ""}`}>
              <span>03</span>
              Detecting suspicious activity...
            </div>

            <div className={`step ${progress >= 80 ? "active" : ""}`}>
              <span>04</span>
              Correlating connected cases...
            </div>

            <div className={`step ${progress >= 100 ? "active" : ""}`}>
              <span>05</span>
              Preparing investigation report...
            </div>

          </div>


          <div className="loading-warning">
            Blockchain analysis may take several moments.
            Do not close the investigation window.
          </div>

        </div>

      </div>
    );
  }


  // =====================================================
  // DASHBOARD
  // =====================================================

  if (showDashboard) {

    const data = investigationData || {};

    return (
      <div className="dashboard-page">

        {/* HEADER */}

        <header className="dashboard-header">

          <div>
            <div className="dashboard-brand">
              CHAKRAVYUH
            </div>

            <div className="dashboard-subtitle">
              BLOCKCHAIN INVESTIGATION SYSTEM
            </div>
          </div>

          <div className="investigation-status">
            ● ANALYSIS COMPLETE
          </div>

        </header>


        {/* INTRO */}

        <section className="dashboard-intro">

          <div>

            <div className="eyebrow">
              INVESTIGATION TARGET
            </div>

            <h1>
              {data.wallet || walletAddress}
            </h1>

            <p>
              Investigation completed successfully
            </p>

          </div>

          <div className="risk-badge">
            {data.risk || "HIGH"} RISK
          </div>

        </section>


        {/* SUMMARY */}

        <section className="summary-grid">

          <div className="summary-card">

            <span>RISK LEVEL</span>

            <strong className="risk-text">
              {data.risk || "HIGH"}
            </strong>

          </div>


          <div className="summary-card">

            <span>TRANSACTIONS</span>

            <strong>
              {data.transactions || 0}
            </strong>

          </div>


          <div className="summary-card">

            <span>BLOCKCHAIN HOPS</span>

            <strong>
              {data.blockchain_hops || 0}
            </strong>

          </div>


          <div className="summary-card">

            <span>SUSPICIOUS POINTS</span>

            <strong>
              {data.suspicious_points || 0}
            </strong>

          </div>

        </section>


        {/* GRAPH */}

        <section className="dashboard-panel graph-panel">

          <div className="panel-heading">

            <div>

              <div className="eyebrow">
                TRANSACTION ANALYSIS
              </div>

              <h2>
                Blockchain Transaction Graph
              </h2>

            </div>

            <div className="panel-tag">
              {data.blockchain_hops || 3} HOPS TRACED
            </div>

          </div>


          <div className="graph-container">

            <TransactionGraph />

          </div>

        </section>


        {/* TWO COLUMNS */}

        <div className="two-column-grid">


          {/* SUSPICIOUS ACTIVITY */}

          <section className="dashboard-panel">

            <div className="eyebrow">
              THREAT ANALYSIS
            </div>

            <h2>
              Suspicious Activity
            </h2>


            <div className="activity-list">

              {data.suspicious_activity?.map(
                (item, index) => (

                  <div
                    className="activity-item"
                    key={index}
                  >

                    <div>

                      <h3>
                        {item.title}
                      </h3>

                      <p>
                        {item.description}
                      </p>

                    </div>

                    <div
                      className={`severity ${
                        item.severity === "HIGH"
                          ? "high"
                          : "medium"
                      }`}
                    >
                      {item.severity}
                    </div>

                  </div>

                )
              )}

            </div>

          </section>


          {/* VASP */}

          <section className="dashboard-panel">

            <div className="eyebrow">
              ENTITY ATTRIBUTION
            </div>

            <h2>
              Nearest VASP / Exchange
            </h2>


            <div className="vasp-card">

              <div className="vasp-icon">
                $
              </div>

              <div className="vasp-info">

                <h3>
                  {data.vasp?.name || "Unknown Exchange"}
                </h3>

                <p>
                  Possible service interaction detected
                </p>

              </div>


              <div className="confidence">

                <strong>
                  {data.vasp?.confidence || 0}%
                </strong>

                <span>
                  CONFIDENCE
                </span>

              </div>

            </div>


            <div className="confidence-bar">

              <div
                className="confidence-fill"
                style={{
                  width: `${data.vasp?.confidence || 0}%`,
                }}
              />

            </div>


            <p className="panel-description">
              Attribution is based on transaction behavior,
              address clustering and known blockchain patterns.
            </p>

          </section>

        </div>


        {/* CASES + EVIDENCE */}

        <div className="two-column-grid">


          {/* CONNECTED CASES */}

          <section className="dashboard-panel">

            <div className="eyebrow">
              CASE CORRELATION
            </div>

            <h2>
              Connected Cases
            </h2>


            <div className="case-list">

              {data.connected_cases?.map(
                (item, index) => (

                  <div
                    className="case-item"
                    key={index}
                  >

                    <div>

                      <h3>
                        CASE #{item.id}
                      </h3>

                      <p>
                        {item.description}
                      </p>

                    </div>

                    <span>
                      {item.type}
                    </span>

                  </div>

                )
              )}

            </div>

          </section>


          {/* EVIDENCE */}

          <section className="dashboard-panel">

            <div className="eyebrow">
              INVESTIGATION RECORD
            </div>

            <h2>
              Evidence
            </h2>


            <div className="evidence-grid">

              <div className="evidence-card">

                <span>01</span>

                <h3>
                  Suspicious transaction transition
                </h3>

                <p>
                  HIGH RISK · TRANSACTION PATH
                </p>

              </div>


              <div className="evidence-card">

                <span>02</span>

                <h3>
                  Rapid movement
                </h3>

                <p>
                  HIGH RISK · FUND MOVEMENT
                </p>

              </div>


              <div className="evidence-card">

                <span>03</span>

                <h3>
                  Potential exchange interaction
                </h3>

                <p>
                  {data.vasp?.confidence || 0}% CONFIDENCE
                </p>

              </div>


              <div className="evidence-card">

                <span>04</span>

                <h3>
                  Connected case correlation
                </h3>

                <p>
                  CASE PATTERN MATCH
                </p>

              </div>


              <div className="evidence-card">

                <span>05</span>

                <h3>
                  Near-total fund forwarding
                </h3>

                <p>
                  HIGH RISK · FUND FORWARDING
                </p>

              </div>

            </div>

          </section>

        </div>


        {/* REPORT */}

        <div className="report-section">

          <button
            className="report-button"
            onClick={generateReport}
          >
            GENERATE INVESTIGATION REPORT
          </button>

        </div>

      </div>
    );
  }


  // =====================================================
  // LANDING PAGE
  // =====================================================

  return (

    <div className="landing-page">


      {/* HEADER */}

      <header className="landing-header">

        <div className="landing-logo">
          CHAKRAVYUH
        </div>

        <div className="landing-system">
          BLOCKCHAIN INVESTIGATION SYSTEM
        </div>

      </header>


      {/* HERO */}

      <main className="hero-section">

        <div className="hero-eyebrow">
          DIGITAL FORENSICS PLATFORM
        </div>


        <h1>

          TRACE THE MONEY.

          <br />

          <span>
            UNCOVER THE TRUTH.
          </span>

        </h1>


        <p className="hero-description">

          Investigate suspicious cryptocurrency transactions,
          trace blockchain movements and discover connected
          fraud cases through an intelligent investigation interface.

        </p>


        {/* WALLET FORM */}

        <div className="wallet-form">

          <input
            type="text"
            value={walletAddress}
            onChange={(e) =>
              setWalletAddress(e.target.value)
            }
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                handleInvestigation();
              }
            }}
            placeholder="Enter wallet address..."
          />


          <button
            onClick={handleInvestigation}
          >
            INVESTIGATE →
          </button>

        </div>


        {error && (

          <div className="error-message">
            {error}
          </div>

        )}


        {!error && (

          <div className="hero-hint">
            Enter a blockchain wallet address to begin investigation.
          </div>

        )}

      </main>

    </div>
  );
}

export default App;